export const menuItems = [
  { id: 1, name: '唐揚定食(学生)', price: 440, calories: 1012, image: '/images/menu/唐揚げ定食.jpg', isActive: true },
  { id: 2, name: '唐揚定食(一般)', price: 510, calories: 1012, image: '/images/menu/唐揚げ定食.jpg', isActive: true },
  { id: 3, name: '温玉唐揚げ丼(学生)', price: 540, calories: 1381, image: '/images/menu/温玉唐揚げ定食.jpg', isActive: true }, // フォルダ内の「温玉唐揚げ定食.jpg」を割り当て
  { id: 4, name: '温玉唐揚げ丼(一般)', price: 610, calories: 1381, image: '/images/menu/温玉唐揚げ定食.jpg', isActive: true },
  { id: 5, name: '日替わり1番(学生)', price: 580, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true },
  { id: 6, name: '日替わり1番(一般)', price: 650, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true },
  { id: 7, name: '日替わり2番(学生)', price: 540, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true },
  { id: 8, name: '日替わり2番(一般)', price: 610, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true },
  { id: 9, name: '日替わり丼(学生)', price: 480, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true },
  { id: 10, name: '日替わり丼(一般)', price: 530, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true },
  { id: 11, name: 'ホッケ定食(学生)', price: 650, calories: null, image: '/images/menu/ホッケ定食.jpg', isActive: true },
  { id: 12, name: 'ホッケ定食(一般)', price: 700, calories: null, image: '/images/menu/ホッケ定食.jpg', isActive: true },
  { id: 13, name: '小盛ご飯唐揚げ定食(学生)', price: 410, calories: null, image: '/images/menu/唐揚げ定食.jpg', isActive: true },
  { id: 14, name: '小盛ご飯唐揚げ定食(一般)', price: 480, calories: null, image: '/images/menu/唐揚げ定食.jpg', isActive: true },
  { id: 15, name: '小盛温玉唐揚げ丼(学生)', price: 510, calories: null, image: '/images/menu/温玉唐揚げ定食.jpg', isActive: true },
  { id: 16, name: '小盛温玉唐揚げ丼(一般)', price: 580, calories: null, image: '/images/menu/温玉唐揚げ定食.jpg', isActive: true },
  { id: 17, name: '小盛日替わり1番(学生)', price: 550, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true },
  { id: 18, name: '小盛日替わり1番(一般)', price: 620, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true },
  { id: 19, name: '小盛日替わり2番(学生)', price: 510, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true },
  { id: 20, name: '小盛日替わり2番(一般)', price: 580, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true },
  { id: 21, name: '小盛日替わり3番(学生)', price: 450, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true },
  { id: 22, name: '小盛日替わり3番(一般)', price: 500, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true },
  { id: 23, name: '小盛日替わり丼(学生)', price: 620, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true },
  { id: 24, name: '小盛日替わり丼(一般)', price: 670, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true },
  { id: 25, name: 'カレーライス', price: 390, calories: 771, image: '/images/menu/カレーライス.jpg', isActive: true },
  { id: 26, name: 'コロッケカレー', price: 470, calories: 814, image: '/images/menu/コロッケカレー.jpg', isActive: true },
  { id: 27, name: '唐揚げ2個カレー', price: 550, calories: 935, image: '/images/menu/唐揚げカレー.jpg', isActive: true }, // フォルダ内の「唐揚げカレー.jpg」を割り当て
  { id: 28, name: 'チキンカツカレー', price: 530, calories: 875, image: '/images/menu/チキンカツカレー.jpg', isActive: true },
  { id: 29, name: 'とんかつカレー', price: 600, calories: 1132, image: '/images/menu/とんかつカレー.jpg', isActive: true },
  { id: 30, name: '半カレー', price: 200, calories: 312, image: '/images/menu/ハーフカレー.jpg', isActive: true }, // フォルダ内の「ハーフカレー.jpg」を割り当て
  { id: 31, name: 'コロッケ丼', price: 380, calories: 1004, image: '/images/menu/コロッケ丼.jpg', isActive: true },
  { id: 32, name: '鶏ソースカツ丼', price: 420, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true },
  { id: 33, name: 'ソースカツ丼', price: 550, calories: 852, image: '/images/menu/ソースとんかつ丼.jpg', isActive: true }, // フォルダ内の「ソースとんかつ丼.jpg」を割り当て
  { id: 34, name: '鬼から定', price: 850, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true },
  { id: 35, name: '炒飯', price: 490, calories: 646, image: '/images/menu/炒飯.jpg', isActive: true },
  { id: 36, name: 'ミニ炒飯', price: 180, calories: 315, image: '/images/menu/ミニ炒飯.jpg', isActive: true },
  { id: 37, name: '曜日別_学生', price: 450, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true },
  { id: 38, name: '曜日別_一般', price: 500, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true },
  { id: 39, name: '単品ライス', price: 170, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true },
  { id: 40, name: 'ご飯類大盛', price: 120, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true },
  { id: 41, name: '麺ダブル', price: 110, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true },
  { id: 42, name: 'ラーメン(しょうゆ)', price: 400, calories: 510, image: '/images/menu/醤油ラーメン.jpg', isActive: true }, // フォルダ内の「醤油ラーメン.jpg」を割り当て
  { id: 43, name: 'ラーメン(みそ)', price: 400, calories: 580, image: '/images/menu/味噌ラーメン.jpg', isActive: true }, // フォルダ内の「味噌ラーメン.jpg」を割り当て
  { id: 44, name: 'ラーメン(しお)', price: 400, calories: 540, image: '/images/menu/塩ラーメン.jpg', isActive: true }, // フォルダ内の「塩ラーメン.jpg」を割り当て
  { id: 45, name: '塩担々麺', price: 480, calories: 631, image: '/images/menu/塩担々麺.jpg', isActive: true },
  { id: 46, name: '限定メニュー', price: 500, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true },
  { id: 47, name: 'かけうどん', price: 280, calories: 396, image: '/images/menu/かけうどん.jpg', isActive: true },
  { id: 48, name: 'かけそば', price: 290, calories: 312, image: '/images/menu/かけそば.jpg', isActive: true },
  { id: 49, name: 'ざるうどん', price: 280, calories: 305, image: '/images/menu/ざるうどん.jpg', isActive: true },
  { id: 50, name: 'ざるそば', price: 290, calories: 362, image: '/images/menu/ざるそば.jpg', isActive: true },
  { id: 51, name: 'きつねうどん', price: 300, calories: 446, image: '/images/menu/きつねうどん.jpg', isActive: true },
  { id: 52, name: 'きつねそば', price: 310, calories: 354, image: '/images/menu/きつねそば.jpg', isActive: true },
  { id: 53, name: '温玉うどん', price: 360, calories: 485, image: '/images/menu/温玉うどん.jpg', isActive: true },
  { id: 54, name: 'カレーうどん', price: 380, calories: 579, image: '/images/menu/カレーうどん.jpg', isActive: true },
  { id: 55, name: 'ザルラーメン', price: 430, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true },
  { id: 56, name: 'ミニサラダ', price: 100, calories: null, image: '/images/menu/ミニサラダ.jpg', isActive: true },
  { id: 57, name: '温泉卵', price: 80, calories: null, image: '/images/menu/温泉卵.jpg', isActive: true },
  { id: 58, name: '味噌汁', price: 50, calories: null, image: '/images/menu/味噌汁.jpg', isActive: true },
  { id: 59, name: '納豆', price: 50, calories: null, image: '/images/menu/納豆.jpg', isActive: true },
  { id: 60, name: '冷奴', price: 80, calories: null, image: '/images/menu/冷奴.jpg', isActive: true },
  { id: 61, name: 'コロッケ', price: 70, calories: null, image: '/images/menu/コロッケ.jpg', isActive: true },
  { id: 62, name: 'ジャンボメンチ', price: 130, calories: null, image: '/images/menu/ジャンボメンチ.jpg', isActive: true },
  { id: 63, name: 'ちくわ天', price: 100, calories: null, image: '/images/menu/ちくわ天.jpg', isActive: true },
  { id: 64, name: '海老かき揚げ', price: 120, calories: null, image: '/images/menu/かき揚げ.jpg', isActive: true }, // フォルダ内の「かき揚げ.jpg」を割り当て
  { id: 65, name: '単品唐揚1個', price: 70, calories: null, image: '/images/menu/単品唐揚.jpg', isActive: true }, // フォルダ内の「単品唐揚.jpg」を割り当て
  { id: 66, name: '単品鶏カツ1個', price: 70, calories: null, image: '/images/menu/チキンカツ.jpg', isActive: true }, // フォルダ内の「チキンカツ.jpg」を割り当て
  { id: 67, name: '週替わり小鉢A', price: 80, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true },
  { id: 68, name: '週替わり小鉢B', price: 100, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true },
  { id: 69, name: '週替わり小鉢C', price: 150, calories: null, image: 'https://placehold.jp/150x100.png?text=test', isActive: true }
];